CREATE TABLE personnages (
classe text NOT NULL,
race text NOT NULL,
lore text NOT NULL,
id_joueur integer,
id_entite integer,
nom_entite text NOT NULL,
niveau integer,
experience integer,
force integer,
dexterite integer,
constitution integer,
intelligence integer,
sagesse integer,
charisme integer,
capacites text,
vie integer,
attaques text,
languages text,
description text
);

INSERT INTO personnages(classe ,
race ,
lore ,
id_joueur ,
id_entite,
nom_entite ,
niveau,
experience,
force,
dexterite,
constitution,
intelligence,
sagesse,
charisme ,
capacites ,
vie ,
attaques ,
languages ,
description) VALUES
('Rabfge', 'Troll','JE suis un oldat',5,5,'ouuii',10,50,2,4,5,6,4,3,'capcatites',5,'attaques','languages','desc')
;
