DROP table Campagne
    ,Donjon
    ,Salle
    ,Cellule
    ,Entite
    ,Capacite
    ,Langage
    ,Attaque
    ,Personnage
    ,Monstre
    ,Objet
    ,Combat
    ,Utilisateur
    ,Jet
    ,FeedBack
    ,Utilisateur_Entite
    ,Utilisateur_Campagne
    ,Entite_Objet
    Cascade;